[build-system]
requires = ["setuptools", "wheel", "numpy"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
markers = [
        "device: Tests require connected real device"
]